name:                firestone
version:             0.1.0.0
github:              "emilgedda/firestone"
license:             BSD3
author:              "Emil Gedda"
maintainer:          "emil.gedda@emilgedda.se"
copyright:           "2018 Emil Gedda"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            A light weight haskell clone of Hearthstone
# category:            Education

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/firestone#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 1.2 && < 2
- containers >= 0.6 && < 1
- pretty-show >= 1.9 && < 2

library:
  source-dirs: src
  default-extensions: OverloadedStrings

executables:
  firestone-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions: OverloadedStrings
    dependencies:
    - firestone

tests:
  firestone-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - firestone
